Repository py-libhdate/py-libhdate, pull requests merged in 2022-10, with the labels that each got.

#102 Fix motzei shabbat
  .pre-commit-config.yaml
  hdate/zmanim.py
Labels: bug, hacktoberfest-accepted

#103 htables French translation.
  hdate/htables.py
Labels: enhancement, hacktoberfest-accepted

#101 Drop support for Python 2
  README.rst
  hdate/common.py
  hdate/htables.py
  hdate/zmanim.py
  poetry.lock
  pyproject.toml
  tests/test_common.py
  tests/test_hdate.py
  tests/test_zmanim.py
  tox.ini
Labels: hacktoberfest-accepted, chore

#107 Move development to 3.7 by default
  .vscode/settings.json
  poetry.lock
  pyproject.toml
Labels: hacktoberfest-accepted, chore
