Repository py-libhdate/py-libhdate, pull requests merged in 2024-11, with the labels that each got.

#134 Deprecate support for Python 3.8, add support for Python 3.13
  .github/workflows/run-tests.yaml
  hdate/location.py
  hdate/zmanim.py
  pdm.lock
  pyproject.toml
  tox.ini
Labels: chore

#135 30th of Kislev should also be considered chanuka
  hdate/htables.py
  tests/test_hdate.py
Labels: bug

#136 Make libhdate fully typed
  .github/release-drafter.yaml
  .gitignore
  .pre-commit-config.yaml
  docs/source/conf.py
  hdate/converters.py
  hdate/date.py
  hdate/hebrew_date.py
  hdate/htables.py
  hdate/location.py
  hdate/zmanim.py
  pdm.lock
  pyproject.toml
  tests/conftest.py
  tests/test_converters.py
  tests/test_hdate.py
  tests/test_hdate_api.py
  tests/test_hdate_string.py
  tests/test_zmanim.py
Labels: code-quality

#140 Fix is_holiday behavior
  hdate/date.py
  hdate/htables.py
  tests/test_hdate.py
Labels: bug, patch

#143 Add helper method for all holiday options
  hdate/htables.py
Labels: enhancement, patch

#142 Add support for night according to Rabenou Tam and mincha gedola according to 30 min
  .vscode/settings.json
  README.rst
  hdate/htables.py
  hdate/zmanim.py
  tests/test_hdate_api.py
Labels: feature

#145 Fix Shabbat after Hag Candle Lighting time
  hdate/zmanim.py
  tests/test_zmanim.py
Labels: bug, patch
