Repository py-libhdate/py-libhdate, pull requests merged in 2024-12, with the labels that each got.

#144 Multilanguage
  README.rst
  hdate/date.py
  hdate/htables.py
  hdate/zmanim.py
  tests/test_hdate.py
  tests/test_hdate_api.py
  tests/test_hdate_string.py
Labels: enhancement, minor, breaking

#148 Change Daf Yomi to use TranslatorMixin
  hdate/date.py
  hdate/htables.py
  hdate/translations/en.json
  hdate/translations/fr.json
  hdate/translations/he.json
  utils/translations.py
Labels: enhancement, patch

#150 Use TranslatorMixin for Holidays
  hdate/date.py
  hdate/htables.py
  hdate/translations/en.json
  hdate/translations/fr.json
  hdate/translations/he.json
  utils/translations.py
Labels: enhancement, code-quality, patch

#152 Use translations.py instead of JSON files for performance
  .github/workflows/run-tests.yaml
  .gitignore
  .pre-commit-config.yaml
  hdate/translations.py
  hdate/translator.py
  pdm.lock
  pyproject.toml
  tox.ini
  utils/translations.py
Labels: enhancement, patch

#153 Change Zmanim to use TranslatorMixin
  README.rst
  hdate/htables.py
  hdate/translations.py
  hdate/translations/en.json
  hdate/translations/fr.json
  hdate/translations/he.json
  hdate/translator.py
  hdate/zmanim.py
  tests/test_hdate_api.py
  tests/test_zmanim.py
  utils/translations.py
Labels: enhancement, code-quality, minor, breaking

#156 Move Days to use TranslatorMixin
  hdate/date.py
  hdate/htables.py
  hdate/translations.py
  hdate/translations/en.json
  hdate/translations/fr.json
  hdate/translations/he.json
  utils/translations.py
Labels: enhancement, code-quality

#157 Reorganize code: separate gematria into a separate module
  hdate/date.py
  hdate/gematria.py
  hdate/htables.py
  tests/test_gematria.py
  tests/test_hdate_string.py
  tests/test_omer.py
Labels: code-quality

#158 Remove unneeded Location __repr__
  hdate/location.py
Labels: code-quality

#159 Make day prefix part of translation string for dow
  hdate/date.py
  hdate/hebrew_date.py
  hdate/translations.py
  hdate/translations/he.json
Labels: code-quality

#160 Improve Zmanim API
  hdate/zmanim.py
  tests/test_hdate_api.py
  tests/test_zmanim.py
Labels: enhancement, minor, breaking
