Repository py-libhdate/py-libhdate, pull requests merged in 2025-01, with the labels that each got.

#164 Simplify holidays API
  .github/release-drafter.yaml
  hdate/date.py
  hdate/hebrew_date.py
  hdate/htables.py
  hdate/translator.py
  tests/test_hdate.py
  tests/test_hdate_api.py
Labels: code-quality, minor, breaking

#162 Add prayer and tekufot
  hdate/tekufot.py
  hdate/translations.py
  hdate/translations/en.json
  hdate/translations/fr.json
  hdate/translations/he.json
  tests/test_tekufot.py
Labels: feature, minor

#165 Create Omer API
  README.rst
  hdate/date.py
  hdate/hebrew_date.py
  hdate/omer.py
  hdate/py.typed
  hdate/translations.py
  hdate/translations/en.json
  hdate/translations/fr.json
  hdate/translations/he.json
  hdate/translator.py
  hdate/zmanim.py
  pdm.lock
  pyproject.toml
  tests/__snapshots__/test_omer.ambr
  tests/test_hdate.py
  tests/test_hdate_api.py
  tests/test_omer.py
Labels: enhancement, minor

#169 Improve test clarity and performance
  hdate/location.py
  hdate/translator.py
  pdm.lock
  pyproject.toml
  tests/__snapshots__/test_omer.ambr
  tests/conftest.py
  tests/test_converters.py
  tests/test_hdate.py
  tests/test_hdate_api.py
  tests/test_omer.py
  tests/test_tekufot.py
  tests/test_translator.py
  tests/test_zmanim.py
Labels: code-quality

#170 Remove heb_date from HDate API
  hdate/date.py
  hdate/zmanim.py
  tests/test_hdate.py
Labels: enhancement, major

#171 Add support for uploading to codecov
  .github/workflows/run-tests.yaml
  tox.ini
Labels: chore, skip-changelog

#174 Make astral a real optional dependency
  .github/workflows/run-tests.yaml
  .gitignore
  pdm.lock
  pyproject.toml
  tests/test_zmanim.py
  tox.ini
Labels: feature, major

#176 Streamline Zmanim API
  hdate/tekufot.py
  hdate/zmanim.py
  tests/__snapshots__/test_hdate_api.ambr
  tests/test_hdate.py
  tests/test_hdate_api.py
  tests/test_zmanim.py
Labels: enhancement, minor

#173 Create minimal documentation
  .gitignore
  .readthedocs.yaml
  CHANGELOG.md
  README.rst
  docs/make.bat
  docs/source/api_reference.rst
  docs/source/conf.py
  docs/source/development.rst
  docs/source/hdate.rst
  docs/source/index.rst
  docs/source/modules.rst
  docs/source/quickstart.rst
  hdate/__init__.py
  hdate/date.py
  hdate/hebrew_date.py
  hdate/translator.py
  pdm.lock
  pyproject.toml
  tests/test_hdate.py
  tests/test_translator.py
  tox.ini
Labels: major

#175 Separate Holiday API
  docs/source/index.rst
  docs/source/quickstart.rst
  docs/source/user_guide.rst
  hdate/__init__.py
  hdate/date.py
  hdate/hebrew_date.py
  hdate/holidays.py
  hdate/htables.py
  hdate/translator.py
  pdm.lock
  pyproject.toml
  tests/conftest.py
  tests/test_converters.py
  tests/test_hdate.py
  tests/test_hebrew_date.py
  tests/test_holidays.py
Labels: enhancement, minor

#179 Separate Daf Yomi API
  .gitignore
  hdate/daf_yomi.py
  hdate/date.py
  hdate/parasha.py
  tests/test_daf_yomi.py
  tests/test_hdate.py
  tests/test_omer.py
  tests/test_parasha.py
Labels: enhancement, code-quality
